### ISSUE TITLE
Weird error message

### ISSUE THREAD

**Issue by cognominal** [jaffa4/perl6parsing#1]
I am trying to use perl6parsing, either by importing or by pasting its code in mine
with the same effet. Note the error message that seems to drop/garble part of
the source code below. 

  my $p =  Perl6::Parsing.new(); # create a new object
  $p.parse("my $p=((-3+2)*5;");  # let us parse this text <br> 

Type 'Perl6::Parsing' is not declared
at sprint-match.p6:1
------> my Perl6::Parsing⏏<4345496384>=((-3+2)_5;
Malformed my
at sprint-match.p6:1
------> my Perl6::⏏Parsing<4345496384>=((-3+2)_5;
    expecting any of:
        scoped declarator

**Comment by jaffa4** [comment]
issue seems to be fixed.

**Comment by cognominal** [comment]
Thx. I forgot the existence of this neat tool. Is this used by jnthn to do syntax highlighting in comma ?

**Comment by jaffa4** [comment]
No idea.
